version: '2'

services:

    mongo:
        image: mongo:3.0

    mongo-admin:
        image: mongo-express:latest
        ports:
         - "8081:8081"

    api:
        build:
            context: ./app-api
        ports:
         - "8080:8080"

